server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
spring:
  http.encoding.charset: UTF-8
  http.encoding.enabled: true
  http.encoding.force: true
  application:
    name: BookinSite
  datasource:
    url: jdbc:mysql://localhost/aloreBooking
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  security:
    user:
      password: "ushu123"
      name: "ushu"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
  properties:
    hibernate.jdbc.time_zone: UTC